### ISSUE TITLE
Can the graphics be exported in html or SVG rather than pdf?

### ISSUE THREAD

**Issue by memartone** [force11/Force11-DecisionTrees#1]
Hi Michael:

Is there any way that the graphics can be exported in something that is easier to post to the web?  

Thanks,

Maryann

**Comment by michbarsinai** [comment]
Sure - PM supports SVG, png, and other formats too (basically, whatever Graphviz supports).

**Comment by michbarsinai** [comment]
@memartone - added .svg and .png visualizations to all three models.
